# ----------------------------
# Makefile Options
# ----------------------------

NAME ?= NOTES
ICON ?= icon.png
DESCRIPTION ?= "A User-friendly text editor made by Randomguy, v1.0"
COMPRESSED ?= YES
ARCHIVED ?= YES

CFLAGS ?= -Wall -Wextra -Oz
# ----------------------------

ifndef CEDEV
$(error CEDEV environment path variable is not set)
endif

include $(CEDEV)/meta/makefile.mk

#------------------------------